### ISSUE TITLE
minSdkVersion怎么是19？

### ISSUE THREAD

**Issue by RavioliWonton** [zhpanvip/viewpagerindicator#11]
[主库](https://github.com/zhpanvip/BannerViewPager/blob/master/build.gradle)那边是16，[这边](https://github.com/zhpanvip/viewpagerindicator/blob/master/indicator/build.gradle)反而是19，到底那一边是对的？强行用在16版本上会不会出错？

**Comment by zhpanvip** [comment]
因为考虑到19以前的手机目前已经非常非常少了，而且绝大部分的app已经最小兼容到21了，所以这个库将最小版本定为了19. BVP引用indicator不会有问题。

**Comment by RavioliWonton** [comment]
好的，我们这边也没有测出来什么错误，不过最好还是统一一下。
