### ISSUE TITLE
设置颜色无效

### ISSUE THREAD

**Issue by qwer2y** [zhpanvip/viewpagerindicator#12]
val indicator = findViewById<IndicatorView>(R.id.indicator_view)
        indicator.apply {
            setSlideMode(IndicatorSlideMode.WORM)
            setIndicatorStyle(IndicatorStyle.CIRCLE)
            setSliderColor(R.color.blue_122, R.color.blue_122)
            setupWithViewPager(pager)
        }

xml:
   <com.zhpan.indicator.IndicatorView
            android:id="@+id/indicator_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:layout_constraintTop_toBottomOf="@id/pager"
            android:layout_marginTop="10dp"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            android:layout_margin="@dimen/dp_10" />

**Comment by zhpanvip** [comment]
颜色值参数错了，接受的是ColorInt。

**Comment by qwer2y** [comment]
解决，感谢

**Comment by KrishuCN** [comment]
> 解决，感谢。

考虑给未选中时的样式添加空心圆吗？

**Comment by qwer2y** [comment]
> 解决，感谢

考虑给未选中时的样式添加空心圆吗？

**Comment by zhpanvip** [comment]
目前没有计划，不满足需求的你可以尝试自定义。

**Comment by qwer2y** [comment]
> 目前没有计划，不满足需求的你可以尝试自定义。

好的 谢谢
