### ISSUE TITLE
找不到setPageSize方法

### ISSUE THREAD

**Issue by YPR2021** [zhpanvip/viewpagerindicator#16]
indicatorView.apply {
                             setSliderColor(normalColor, checkedColor)
                             setSliderWidth(resources.getDimension(R.dimen.dp_10))
                             setSliderHeight(resources.getDimension(R.dimen.dp_5))
                             setSlideMode(IndicatorSlideMode.WORM)
                             setIndicatorStyle(IndicatorStyle.CIRCLE)
                             setPageSize(view_pager2!!.adapter!!.itemCount)
                             notifyDataChanged()
                         }
这个 setPageSize(view_pager2!!.adapter!!.itemCount)方法找不到  1.2.0版本

**Comment by zhpanvip** [comment]
测试了一下，这个方法是没有问题的。

**Comment by YPR2021** [comment]
只有setViewPage

**Comment by zhpanvip** [comment]
你检查下你是不是将Indicator声明称IIndicator接口了？接口里边确实没有这个方法，需要声明成BaseIndicatorView或者继承BaseIndicatorView。

**Comment by YPR2021** [comment]
噢噢，是的。解决了
