### ISSUE TITLE
viewpager只有一个时，indicator不显示

### ISSUE THREAD

**Issue by oarage** [zhpanvip/viewpagerindicator#17]
viewpager只有一个时，indicator不显示
有多项时，indicator才显示

**Comment by zhpanvip** [comment]
只有一个item时，没有绘制indicator。

**Comment by j-gin** [comment]
> 只有一个item时，没有绘制indicator。

现要与iOS保持一致，怎么修改才能让只有一个item时也绘制indicator

**Comment by zhpanvip** [comment]
暂时没计划支持这个需求，你可以下载源码修改

**Comment by j-gin** [comment]
> 暂时没计划支持这个需求，你可以下载源码修改

你好，谢谢回复
我改了这三个地方，目前已经调出，但会有其他影响吗
![image](https://user-images.githubusercontent.com/23333288/121313235-c5deda00-c938-11eb-9c00-c408f7b2303a.png)
![image](https://user-images.githubusercontent.com/23333288/121313305-d8591380-c938-11eb-8d4d-15a0a54955f0.png)
![image](https://user-images.githubusercontent.com/23333288/121313444-f888d280-c938-11eb-886a-4ae4704cb194.png)

**Comment by DylanCaiCoding** [comment]
> 现要与iOS保持一致，怎么修改才能让只有一个item时也绘制indicator

不应该让 iOS 改得和 Android 保持一致吗，哈哈。又不能滑动，有指示器很奇怪耶

**Comment by j-gin** [comment]
> > 现要与iOS保持一致，怎么修改才能让只有一个item时也绘制indicator
> 
> 不应该让 iOS 改得和 Android 保持一致吗，哈哈。又不能滑动，有指示器很奇怪耶

iOS小伙伴说要计算高度，不好改、不想改、不改，总的一个人妥协啊，所以、我妥协了。

**Comment by zhpanvip** [comment]
v1.2.1新增了一个接口showIndicatorWhenOneItem(boolean) ，可以支持一个item时显示指示器

**Comment by j-gin** [comment]
> v1.2.1新增了一个接口showIndicatorWhenOneItem(boolean) ，可以支持一个item时显示指示器

牛逼！V5
