### ISSUE TITLE
Suggestion : Drawable indicator is not a part of Library..

### ISSUE THREAD

**Issue by iamAliRaza** [zhpanvip/viewpagerindicator#18]
You should add Drawable Indicator inside library...

Thanks

**Comment by zhpanvip** [comment]
You need copy DrawableIndicator from sample code. https://github.com/zhpanvip/viewpagerindicator/blob/master/app/src/main/java/com/zhpan/viewpagerindicator/DrawableIndicator.kt

**Comment by iamAliRaza** [comment]
Yup .. I copied already but i was thinking it would be a part of library .... So that;s why i posted here as a suggestion that if you would add these helpers classes as a part of library so it would be easy for developers ...

**Comment by zhpanvip** [comment]
Thanks for your suggstion.
This library mainly provides indicators of different styles and different sliding modes as shown in homepage table. Also ,it  provides good extension funtions,you can implement any style you want by custom indicator easily. DrawableIndicator is only one of these custom indicators,but not the part of this library.So Ithink It will not be added in library. if need,just copied DrawableIndicator from sample or customized yourself indicator by extends BaseIndicatorView.

**Comment by iamAliRaza** [comment]
ok thanks Up to you 👍🏻
