### ISSUE TITLE
SCALE 模式无效果。

### ISSUE THREAD

**Issue by hnlbxb2004** [zhpanvip/viewpagerindicator#21]
indicatorView.setSliderColor(Color.parseColor("#ffffff"),Color.parseColor("#1FC0EB"))
indicatorView.setSlideMode(IndicatorSlideMode.SCALE)
indicatorView.setIndicatorStyle(IndicatorStyle.ROUND_RECT)
indicatorView.setSliderHeight(20f)
indicatorView.setSliderWidth(30.0f,30.0f)

我测试了，只要Mode 为SCALE 就无效。

**Comment by zhpanvip** [comment]
设置了SCALE模式，为什么还要把选中与未选中的长度设置称一样长？
