### ISSUE TITLE
你好，我想请教一下关于指示器不生效

### ISSUE THREAD

**Issue by RyensX** [zhpanvip/viewpagerindicator#23]
地址
https://github.com/RyensX/MediaBox/blob/95cf9330505618f09b2fcb0f9693cde4e5ae096e/app/src/main/java/com/su/mediabox/view/viewcomponents/BannerViewHolder.kt#L109
排查了vp2、adpater和pageSize都没问题
几个commit之前都没问题，现在百思不得其解为什么突然无效了

**Comment by zhpanvip** [comment]
没改指示器版本的话大概率是你带吗的问题
