### ISSUE TITLE
drawScaleSlider

### ISSUE THREAD

**Issue by StevenHia** [zhpanvip/viewpagerindicator#30]
I get Error..
![image](https://github.com/zhpanvip/viewpagerindicator/assets/45889358/7c354943-f394-4580-802e-bb67b1b9c0f4)

I just added   setIndicatorStyle(IndicatorStyle.CIRCLE) and setSlideMode(IndicatorSlideMode.SCALE)
![image](https://github.com/zhpanvip/viewpagerindicator/assets/45889358/faa7ae51-db41-4bf6-a0c4-b76f6e097deb)

How to fixing???

**Comment by zhpanvip** [comment]
try to use v1.2.3
