### ISSUE TITLE
单独使用

### ISSUE THREAD

**Issue by meanhan** [zhpanvip/viewpagerindicator#6]
可以不结合ViewPager,单独使用吗？

**Comment by zhpanvip** [comment]
你要结合什么使用？

**Comment by meanhan** [comment]
recyclerView ，就是可以自己控制数量 和左右   不跟随ViewPager

**Comment by zhpanvip** [comment]
建议你还是使用ViewPager2.使用RecyclerView的话需要你自己计算一些滑动数据给到indicator.会比较麻烦。
