### ISSUE TITLE
The indicators at the bottom and the last one on the right are cut off

### ISSUE THREAD

**Issue by akhbulatov** [zhpanvip/viewpagerindicator#7]
Hi. In the library sample, as you can see in the attached screenshot, the indicators at the bottom and the last one on the right are also cut off.

<img width="342" alt="Снимок экрана 2020-10-17 в 02 04 38" src="https://user-images.githubusercontent.com/6171938/96321234-499c2d00-101d-11eb-8b2f-58766e28752f.png">

**Comment by zhpanvip** [comment]
OK,I will fix it in the next version.

**Comment by zhpanvip** [comment]
May I Know what your phone model you are using? I test with my HuaWei and Samsung phone，It looks well.

And I added padding to the indicator in the commit just now to try to fix it. You can Pull the latest code  to test whether it has been fixed.

**Comment by akhbulatov** [comment]
I have Pixel 3a. I downloaded the last apk of the sample and now everything is ok, nothing is cut off.

**Comment by zhpanvip** [comment]
1.0.6 released
