### ISSUE TITLE
while adding library to gradle giving me this error

### ISSUE THREAD

**Issue by Usama75** [zhpanvip/viewpagerindicator#8]
Checksum failed for [androidx.core:core:1.1.0, 76c7cfbe596fe3c09a6983bf1c89e889299c08ac9a3b52ce5182a088d056647e]
how can I fix this?

**Comment by zhpanvip** [comment]
There seems to be no problem with this library, please check your project enviroment,such as the version of androidx.
ViewPagerIndicator implementation "androidx.core:core-ktx:1.3.1"
